### ISSUE TITLE
iUFCExport - inbound issue

### ISSUE THREAD

**Issue by ML1872** [wluc9875/iUFCExport-LuaScript#1]
Hi,  I have recently downloaded excellent iUFCExport app onto my ipad.  It did not work initially, So I changed the export host in the lua file to my ipad IP address with 255 at the end, as recommended.
I can now see the control panel live on my ipad, but cannot input any controls to the UFC via the ipad.
Grateful for any advice on what to do next to resolve the inbound issue.
Many thanks
ML

**Comment by spandexcowboy** [comment]
I had the same issue , both on using the .255 and using the actual IP address of my IPAD

What fixed it for me was adding the same IP into the app config (top right from the plane selection screen)
