### ISSUE TITLE
Lag introduced by Script in DCS 2.8+

### ISSUE THREAD

**Issue by DenisLaubert** [wluc9875/iUFCExport-LuaScript#4]
Since DCS 2.8 I happen to see that the script as soon as running 

`local iUFClfs=require('lfs');
dofile(iUFClfs.writedir()..'Scripts/iUFCExport.lua')`

is introducing a lot of frame drops and lags in DCS. 
I have not found any solution for the issue by now. Does anyone have the same issue?

**Comment by DexterHaslem** [comment]
After doing some cross-comparisons, I get an avg of 85 fps with the script disabled (by simply commenting out eg `--dofile(iUFClfs.writedir()..'Scripts/iUFCExport.lua')`). 

As soon as I re-enable, the exact same scenario i get 50 fps avg, with bad spikes to 40s here and there. 

I'm gunna give it a shot and see if there is anything obvious going on to fix since 2.8 as I love this thing :)

**Comment by DexterHaslem** [comment]
hrm well, I think I fixed the big performance hits with a few low-hanging fruit fixes, and still a few more to go.
however i've hit a wall, while my ipad receives updates from dcs, it no longer sends anything on the network on any IP settings (broadcast, mcast, actual ip, etc..) , unrelated to this. I can't verify updates from ipad->dcs are still responsive enough. I guess consider this a warning to not update to ipados 16+ too ?!

anyway, if you have a currently working both ways setup and want to help test my changes you can see it here https://github.com/DexterHaslem/iUFCExport-LuaScript/blob/11009d4204d4a67a9a2700e696c2d32eff5cda67/iUFCExport.lua

**Comment by DenisLaubert** [comment]
> hrm well, I think I fixed the big performance hits with a few low-hanging fruit fixes, and still a few more to go. however i've hit a wall, while my ipad receives updates from dcs, it no longer sends anything on the network on any IP settings (broadcast, mcast, actual ip, etc..) , unrelated to this. I can't verify updates from ipad->dcs are still responsive enough. I guess consider this a warning to not update to ipados 16+ too ?!
> 
> anyway, if you have a currently working both ways setup and want to help test my changes you can see it here https://github.com/DexterHaslem/iUFCExport-LuaScript/blob/11009d4204d4a67a9a2700e696c2d32eff5cda67/iUFCExport.lua

Awesome! It works like a charm again. No lag left over on my end. 👍
